# time stamp
std_msgs/Header header
# accelerometer x
float32 accel_x
# accelerometer y
float32 accel_y
# accelerometer z
float32 accel_z
# gyroscope x 
float32 gyro_x
# gyroscope y 
float32 gyro_y
# gyroscope z
float32 gyro_z
# magnetometer x
float32 mag_x
# magnetometer y
float32 mag_y
# magnetometer z
float32 mag_z
# linear acceleration x
float32 lin_accel_x
# linear acceleration y
float32 lin_accel_y
# linear acceleration z
float32 lin_accel_z
# gravity x 
float32 grav_x
# gravity y
float32 grav_y
# gravity z
float32 grav_z
# rotation vector i
float32 rot_vec_i
# rotation vector j
float32 rot_vec_j
# rotation vector k
float32 rot_vec_k
# geomagnetic rotation vector i
float32 geomag_rot_vec_i
# geomagnetic rotation vector j
float32 geomag_rot_vec_j
# geomagnetic rotation vector k
float32 geomag_rot_vec_k
# raw accelerometer x
float32 raw_accel_x
# raw accelerometer y
float32 raw_accel_y
# raw accelerometer z
float32 raw_accel_z
# raw gyroscope x
float32 raw_gyro_x
# raw gyroscope y
float32 raw_gyro_y
# raw gyroscope z
float32 raw_gyro_z
# raw magnetometer x 
float32 raw_mag_x
# raw magnetometer y
float32 raw_mag_y
# raw magnetometer z
float32 raw_mag_z
